name: Update Issue count on a CRON Schedule

on:
  schedule:
    # Runs "20 minutes after midnight, just a bit after Next.js stale issues are closed" (see https://crontab.guru/#20_0_*_*_*)
    # https://github.com/vercel/next.js/blob/a0275f27508d5d726d8afb9ef472068b66f3484c/.github/workflows/stale.yml#L5
    - cron: "20 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Issue count
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        env:
          SECRET: ${{ secrets.SECRET }}
        # Hit the webhook endpoint to add the last day's issue count
        run: |
          curl \
            --request POST \
            --header 'Content-Type: application/json' \
            --data '{ "secret": "'$SECRET'" }' \
            --fail \
            https://nextjs-issue-tracker.vercel.app/api/populate
